"""Mock SmartFlow platform: drives our /ws exactly as SmartFlow's Bi-Directional
Audio Streaming spec describes, with real speech generated by Sarvam TTS.

Run from backend/ while the server is up:
    uv run python tests/mock_smartflow_client.py
"""

import argparse
import asyncio
import base64
import io
import json
import os
import sys
import time
import uuid
import wave
from pathlib import Path

import aiohttp
import websockets
from dotenv import load_dotenv

BACKEND_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND_DIR))
load_dotenv(BACKEND_DIR / ".env", override=True)

from pipecat.audio.utils import create_stream_resampler, pcm_to_ulaw, ulaw_to_pcm  # noqa: E402

from helpers import db  # noqa: E402
from helpers.prompts import DEFAULT_CONTEXT  # noqa: E402

RATE = 8000
FRAME_BYTES = 800              # SmartFlow sends media every 100 ms → 800 mulaw bytes
ULAW_SILENCE = b"\xff"
OUTPUT_DIR = Path(__file__).resolve().parent / "output"

DEFAULT_UTTERANCES = [
    "English is fine.",
    "Yes, I know about the payment. I will pay it by next Monday.",
]
LONG_REPLY_PROMPT = "Before that, can you explain what exactly this payment is for and what services it covers?"
INTERRUPT_UTTERANCE = "Sorry, wait, can you tell me the amount again?"


async def synthesize(session: aiohttp.ClientSession, text: str) -> bytes:
    """Sarvam TTS → 8 kHz mulaw bytes (stands in for the caller's voice)."""
    async with session.post(
        "https://api.sarvam.ai/text-to-speech",
        headers={"api-subscription-key": os.environ["SARVAM_API_KEY"]},
        json={
            "text": text,
            "target_language_code": "en-IN",
            "speaker": "shubh",
            "model": "bulbul:v3",
        },
    ) as resp:
        if resp.status != 200:
            raise RuntimeError(f"Sarvam TTS failed ({resp.status}): {await resp.text()}")
        data = await resp.json()
    with wave.open(io.BytesIO(base64.b64decode(data["audios"][0]))) as wf:
        pcm, rate = wf.readframes(wf.getnframes()), wf.getframerate()
    return await pcm_to_ulaw(pcm, rate, RATE, create_stream_resampler())


class MockSmartFlow:
    def __init__(self, ws, stream_sid: str):
        self.ws = ws
        self.stream_sid = stream_sid
        self.seq = 0
        self.outgoing = bytearray()
        self.bot_audio = bytearray()
        self.media_events: list[float] = []
        self.clears: list[float] = []
        self.bad_sizes: list[int] = []
        self.bad_sids: set[str] = set()
        self.other_events: list[dict] = []

    async def send(self, message: dict):
        self.seq += 1
        message["sequenceNumber"] = str(self.seq)
        await self.ws.send(json.dumps(message))

    async def sender(self):
        chunk, started = 0, time.monotonic()
        while True:
            frame = bytes(self.outgoing[:FRAME_BYTES])
            del self.outgoing[:FRAME_BYTES]
            frame += ULAW_SILENCE * (FRAME_BYTES - len(frame))
            chunk += 1
            await self.send({
                "event": "media",
                "media": {
                    "chunk": str(chunk),
                    "timestamp": str(int((time.monotonic() - started) * 1000)),
                    "payload": base64.b64encode(frame).decode(),
                },
                "streamSid": self.stream_sid,
            })
            await asyncio.sleep(0.1)

    async def receiver(self):
        async for raw in self.ws:
            msg = json.loads(raw)
            event = msg.get("event")
            if msg.get("streamSid") != self.stream_sid:
                self.bad_sids.add(str(msg.get("streamSid")))
            if event == "media":
                payload = base64.b64decode(msg["media"]["payload"])
                if len(payload) % 160:
                    self.bad_sizes.append(len(payload))
                self.bot_audio += payload
                self.media_events.append(time.monotonic())
            elif event == "clear":
                self.clears.append(time.monotonic())
            else:
                self.other_events.append(msg)

    def last_media_age(self) -> float:
        return time.monotonic() - self.media_events[-1] if self.media_events else float("inf")

    async def wait_bot_turn(self, after: float, start_timeout: float = 25.0, gap: float = 1.5) -> bool:
        """Wait until the bot starts sending audio after `after`, then until it goes quiet."""
        deadline = time.monotonic() + start_timeout
        while not (self.media_events and self.media_events[-1] > after):
            if time.monotonic() > deadline:
                return False
            await asyncio.sleep(0.05)
        while self.last_media_age() < gap:
            await asyncio.sleep(0.05)
        return True

    async def say(self, audio: bytes) -> float:
        self.outgoing += audio
        while self.outgoing:
            await asyncio.sleep(0.05)
        return time.monotonic()


async def main(args):
    checks: list[tuple[str, bool, str]] = []

    def check(name: str, ok: bool, detail: str = ""):
        checks.append((name, ok, detail))
        print(f"  {'PASS' if ok else 'FAIL'}  {name}{' — ' + detail if detail else ''}")

    await db.init_db()
    ref_id = f"mock-{uuid.uuid4().hex[:12]}"
    ctx = {**DEFAULT_CONTEXT, "customer_name": "Mock Customer", "amount": "12,345"}
    await db.insert_call(ref_id, "+919999999999", ctx)

    first_text, last_text = DEFAULT_UTTERANCES
    async with aiohttp.ClientSession() as session:
        print("Synthesizing caller audio…")
        first, last = [await synthesize(session, t) for t in DEFAULT_UTTERANCES]
        if args.interrupt:
            long_prompt = await synthesize(session, LONG_REPLY_PROMPT)
            interrupt = await synthesize(session, INTERRUPT_UTTERANCE)
    user_turns = 4 if args.interrupt else 2

    stream_sid = f"MZ{uuid.uuid4().hex}"
    call_sid = f"CA{uuid.uuid4().hex}"
    print(f"Connecting to {args.url}  ref_id={ref_id}")

    async with websockets.connect(args.url) as ws:
        sf = MockSmartFlow(ws, stream_sid)
        await ws.send(json.dumps({"event": "connected"}))
        await sf.send({
            "event": "start",
            "start": {
                "accountSid": "ACmock",
                "streamSid": stream_sid,
                "callSid": call_sid,
                "from": "+911234567890",
                "to": "+919999999999",
                "direction": "outbound",
                "mediaFormat": {"encoding": "audio/x-mulaw", "sampleRate": 8000, "bitRate": 64, "bitDepth": 8},
                "customParameters": {"ref_id": ref_id},
            },
            "streamSid": stream_sid,
        })
        tasks = [asyncio.create_task(sf.sender()), asyncio.create_task(sf.receiver())]

        print("Waiting for greeting…")
        check("bot greeting received", await sf.wait_bot_turn(after=0))

        print(f"Caller says: {first_text!r}")
        check(f"bot replied to {first_text!r}", await sf.wait_bot_turn(after=await sf.say(first)))

        if args.interrupt:
            print(f"Caller says: {LONG_REPLY_PROMPT!r} — then talks over the answer")
            spoken_at = await sf.say(long_prompt)
            deadline = time.monotonic() + 25
            while not (sf.media_events and sf.media_events[-1] > spoken_at) and time.monotonic() < deadline:
                await asyncio.sleep(0.05)
            check("bot started answering the long question", bool(sf.media_events) and sf.media_events[-1] > spoken_at)
            await asyncio.sleep(1.5)
            interrupted_at = time.monotonic()
            print(f"Caller interrupts: {INTERRUPT_UTTERANCE!r}")
            sf.outgoing += interrupt
            deadline = time.monotonic() + 8
            while not any(t > interrupted_at for t in sf.clears) and time.monotonic() < deadline:
                await asyncio.sleep(0.05)
            check("bot sent 'clear' when interrupted", any(t > interrupted_at for t in sf.clears))
            while sf.outgoing:
                await asyncio.sleep(0.05)
            check("bot answered after being interrupted", await sf.wait_bot_turn(after=time.monotonic()))

        print(f"Caller says: {last_text!r}")
        check(f"bot replied to {last_text!r}", await sf.wait_bot_turn(after=await sf.say(last)))

        await sf.send({
            "event": "stop",
            "stop": {"accountSid": "ACmock", "callSid": call_sid, "reason": "The caller disconnected the call"},
            "streamSid": stream_sid,
        })
        await asyncio.sleep(0.5)
        for t in tasks:
            t.cancel()

    check("every outbound media payload is a multiple of 160 bytes",
          not sf.bad_sizes, f"bad sizes: {sorted(set(sf.bad_sizes))[:10]}" if sf.bad_sizes else f"{len(sf.media_events)} media events")
    check("every outbound event carries our streamSid", not sf.bad_sids, ", ".join(sf.bad_sids))
    if sf.other_events:
        print(f"  note: other events from bot: {[e.get('event') for e in sf.other_events]}")

    OUTPUT_DIR.mkdir(exist_ok=True)
    out = OUTPUT_DIR / f"{ref_id}_bot_received.wav"
    pcm = await ulaw_to_pcm(bytes(sf.bot_audio), RATE, RATE, create_stream_resampler())
    with wave.open(str(out), "wb") as wf:
        wf.setnchannels(1); wf.setsampwidth(2); wf.setframerate(RATE); wf.writeframes(pcm)
    print(f"Bot audio as received by 'SmartFlow': {out}")

    print("Waiting for server to persist the call…")
    call = None
    for _ in range(40):
        call = await db.get_call(ref_id)
        if call and call["status"] in ("completed", "failed"):
            break
        await asyncio.sleep(0.5)
    transcript = await db.get_transcript(ref_id)
    check("call marked completed in DB", bool(call) and call["status"] == "completed",
          f"status={call and call['status']} error={call and call['error']}")
    check("callSid/streamSid stored", bool(call) and call["call_sid"] == call_sid and call["stream_sid"] == stream_sid)
    check("transcript stored", len(transcript) >= 1 + user_turns, f"{len(transcript)} turns")
    check("server recording written",
          bool(call) and bool(call["recording_path"]) and Path(call["recording_path"]).is_file(),
          str(call and call["recording_path"]))

    print("\nTranscript:")
    for t in transcript:
        print(f"  {t['role']:>9}: {t['text']}")

    await db.close_db()
    failed = [name for name, ok, _ in checks if not ok]
    print(f"\n{len(checks) - len(failed)}/{len(checks)} checks passed")
    return 1 if failed else 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--url", default=f"ws://127.0.0.1:{os.getenv('PORT', '8011')}/ws")
    parser.add_argument("--no-interrupt", dest="interrupt", action="store_false")
    sys.exit(asyncio.run(main(parser.parse_args())))
